### ISSUE TITLE
Extending repository class

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm-typedi-extensions#1]
I wonder how to easily extend `Repository<T>` class. I tried normal extend:

``` typescript
@Service()
export class UserRepository extends Repository<User> { 
    public findByEmail(email: string): Promise<User | undefined> {
        return this.findOne({ email: email });
    }
}
```

But it throws error about missing metadata and connection stuffs - TypeDI can't figure out by itself that it should call super constructor and inject some stuffs there to make it work.

So I try to create instantion of super class by calling a super constructor:

``` typescript
@Service()
export class UserRepository extends Repository<User> {

    public constructor(@OrmConnection() connection: Connection) {
        super(connection, connection.getMetadata(User));
    }

    public findByEmail(email: string): Promise<User | undefined> {
        return this.findOne({ email: email });
    }
}
```

And it works great but it's a boilerplate which I had to copy-paste in all other repository for my entities.

And also this dependency injection isn't solving testability problem - I don't know how to mock `OrmConnection` and test my `findByEmail` method by mocking `findOne` method.

**Comment by pleerock** [comment]
> export class UserRepository extends Repository<User>

this won't work because type information will be removed by typescript and we cant use "User" here from generic anyhow. Maybe there is some alternative solution without having such constructor, that needs extra implementation, I need to think about it

> And also this dependency injection isn't solving testability problem - I don't know how to mock OrmConnection and test my findByEmail method by mocking findOne method.

mmm... I need to check... if you do `new Repository(mockConnection)` it will not work?

**Comment by 19majkel94** [comment]
> mmm... I need to check... if you do new Repository(mockConnection) it will not work?

It will work if I mock half of the TypeORM... which field and methods from `Connection` should I implement to make it work?

I can only do dummy mocks, like:
```typescript
const connectionMock = {
    getMetadata: () => {},
}
const userRepositoryMock = new UserRepository(connectionMock as any);
```
But then I got many errors like `'TypeError: Cannot read property 'table' of undefined'​​`.

So now I have this dumb code:
```typescript
const connectionMock = {
    getMetadata: () => {},
};

const originalRepository = new UserRepository(connectionMock as any);

const userRepositoryMock = {
    findOne: (object: any) => {
        if (object.email === "test@mail.pl") {
            // blah blah
            return dbUserMock;
        } else {
            return undefined;
        }
    },
    findByEmail: originalRepository.findByEmail
}
```
And it works but it's pain in not a good looking solution 😞

**Comment by pleerock** [comment]
I'll investigate this question

**Comment by pleerock** [comment]
If you want to extend a repositories there are [custom repositories](https://github.com/typeorm/typeorm/tree/master/sample/sample33-custom-repository) support now.

**Comment by 19majkel94** [comment]
Great, I will try it out soon! 😄

**Comment by 19majkel94** [comment]
Looks like `@EntityRepository` is working now thanks to my PR #4 😄 Closing 🔒
