### ISSUE TITLE
Update it to use latest TypeDI (0.5.0)

### ISSUE THREAD

**Issue by slavafomin** [typeorm/typeorm-typedi-extensions#10]
Hello!

Looks like this module depends on functionality removed/renamed from/in TypeDI 0.5.0, specifically: `Container.registerParamHandler` and `Container.registerPropertyHandler`.

Could you please update it?

--

Looks like you've renamed some methods and are now using single method instead of these two. Maybe we should add those methods to TypeDI for backward compatibility and mark them as `@deprecated`? Or just update all depending modules?

**Comment by pleerock** [comment]
simple update in this library is enough. these methods arent widely used if used at all.
