### ISSUE TITLE
typeorm-typedi-extensions@0.0.12 requires a peer of typeorm@^0.0.11 but none was installed.

### ISSUE THREAD

**Issue by ghost** [typeorm/typeorm-typedi-extensions#13]
I get this warning after npm install.

"routing-controllers": "^0.7.0-alpha.11",
    "typedi": "^0.5.2",
    "typeorm": "0.1.0-alpha.19",
    "typeorm-typedi-extensions": "0.0.12",

**Comment by pleerock** [comment]
yeah most probably you'll continue to have this warning before 0.1.0 release... its just a warning, so simply ignore it for now
