### ISSUE TITLE
[Question] Can inject connection, but which one?

### ISSUE THREAD

**Issue by luchillo17** [typeorm/typeorm-typedi-extensions#15]
According to TypeORM docs on connections, we can use multiple connections, you can inject the connection with the TypeDI injector, however which connection get's injected when multiple connections were initialized? the one used to request the repository?

**Comment by pleerock** [comment]
`default` connection is getting injected. You can specify connection name to decorator if you want to inject different connection.

**Comment by luchillo17** [comment]
What if i want it to be dynamic based on a parameter of the request? say i pass the connection name in a JWT token, then the server should be able to execute the query against the mentioned connection.

**Comment by pleerock** [comment]
then inject connection manager instead and use `manager.get(dynamicConnectionName)` instead.

**Comment by luchillo17** [comment]
Indeed, that's the way, thanks.
