### ISSUE TITLE
Can you use custom Repository alone with typedi Container?

### ISSUE THREAD

**Issue by stonecold123** [typeorm/typeorm-typedi-extensions#19]
Does the custom repository only work in another repository? Can I use it alone with the Container from `typeid`?
The following code would throw  something along the line `Cannot read property 'findOne' of undefined`.

 ````
   @Get("/test")
    @ContentType("application/json")
    async testing() {
        let repository = Container.get(UserRepository);
        return await repository.findByEmail('xxx');
    }
````
````
@Service()
@EntityRepository(User)
export class UserRepository extends Repository<User> {
    
    public findByEmail(email: string) {
        return this.findOne({ email });
    }
    
}

@Service()
export class PostService {

    // using constructor injection
    constructor(
        @OrmRepository()
        private readonly userRepository: UserRepository,
    ) {}

    public userExist(user: User): boolean {
        return this.userRepository.findByEmail(user.email) ? true : false;
    }

}
````

**Comment by pleerock** [comment]
From my original design custom repositories couldn't work with containers. But @19majkel94 changed this behaviour, am I right?

**Comment by 19majkel94** [comment]
Problem with containers it that repositories need `manager`, `metadata` and `queryRunner` to work. Container just resolve constructor injections but `Repository` has no injection, there is:
```ts
Object.assign(repository, {
    manager: manager,
    metadata: metadata,
    queryRunner: queryRunner,
});
```
under the hood.

`@OrmRepository()` calls `connection.getRepository` because TypeORM handles the repository dependencies by itself. **So short answer**: no, this extensions exist because of reasons.

**Comment by peterbabic** [comment]
@19majkel94 so it is still impossible to use `Container.get(MyCustomRepository)` instead of `getCustomRepository(MyCustomRepository)`? I want to do `Container.set(MyCustomRepositoryMock)` in the tests. Thank You

**Comment by pbn4** [comment]
Same here.

**Comment by seawatts** [comment]
Any updates here?
