### ISSUE TITLE
Renaming decorators

### ISSUE THREAD

**Issue by 19majkel94** [typeorm/typeorm-typedi-extensions#23]
I think that it would be better if we rename the `@OrmRepository`, `@OrmManager` and `@OrmConnection` decorators.

TypeDI has `@Inject` decorator so we should be consistent with this: `@InjectRepository`, `@InjectManager` and `@InjectConnection` 😉 [Other libs](https://github.com/nestjs/typeorm/blob/master/lib/typeorm.decorators.ts) has the same convention.

@pleerock What do you think about this?

**Comment by pleerock** [comment]
I don't like that they are longer then they were, but yeah it sounds logically correct. We can do that.

**Comment by 19majkel94** [comment]
Closed by #24
