### ISSUE TITLE
UNMET PEER DEPENDENCY typeorm@0.0.9

### ISSUE THREAD

**Issue by valVk** [typeorm/typeorm-typedi-extensions#3]
Subj.
Typeorm@0.0.9 installed but npm did not trust me

![selection_20170307_f6ab2f6](https://cloud.githubusercontent.com/assets/1130626/23657437/b862a260-0346-11e7-876a-2617547c4904.png)

**Comment by pleerock** [comment]
should be fixed in `0.0.9`, thanks to @19majkel94
