### ISSUE TITLE
Update typedi dependency

### ISSUE THREAD

**Issue by kallaspriit** [typeorm/typeorm-typedi-extensions#30]
Please update `typedi` peer dependency to `^0.8.0` (currently `"typedi": "^0.7.2"`).

**Comment by kallaspriit** [comment]
Any plans for this? Would a PR help?

I have used it with the new versions and seems to work fine but don't like the incorrect peer dependency warning.

**Comment by XBeg9** [comment]
Same here, I hate this peer dependency warning. Could we update?

**Comment by XBeg9** [comment]
@pleerock Looks like 0.2.2 has the fix for dependencies, but it's not released (published) to npmjs. Could you please publish the latest master? Thanks

**Comment by XBeg9** [comment]
@pleerock Looks like 0.2.2 has the fix for dependencies, but it's not released (published) to npmjs. Could you please publish the latest master? Thanks

**Comment by pleerock** [comment]
published in typeorm-typedi-extensions@0.2.3

**Comment by RodolfoSilva** [comment]
Thanks @pleerock
