### ISSUE TITLE
question: decorator parameters vs constructor ?

### ISSUE THREAD

**Issue by zecka** [typeorm/typeorm-typedi-extensions#42]
I don't understand the difference between use decorator parameters or decorator in constructor.

I mean différence beetween that:
 ```ts
@Service()
export class PostRepository {
    constructor(
        @InjectRepository(Post)
        private repository: Repository<Post>
    ) {} 
}
```
And that
 ```ts
@Service()
export class PostRepository {
       @InjectRepository(Post)
        private repository: Repository<Post>
}
```

When should I use the constructor, is there a solution that should be prioritized?

**Comment by NoNameProvided** [comment]
You can use whichever you like. There is a small technical difference between the two methods:

- When using parameter injection the class is created first (constructor finished running) and TypeDI resolves the property params only after the instance has been created
- When using constructor injection the parameters are created first and only after your target class is created.
