### ISSUE TITLE
fix: incorrect repository URL in package.json

### ISSUE THREAD

**Issue by glen-84** [typeorm/typeorm-typedi-extensions#46]
Changed here: https://github.com/typeorm/typeorm-typedi-extensions/commit/d5644a037f62425ef4e7a11396d4aa03d88f4acf#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L19-R14.

**Comment by NoNameProvided** [comment]
Good catch! Care to open a PR for it?
