### ISSUE TITLE
OrmCustomRepository does not exist anymore ?

### ISSUE THREAD

**Issue by booradleys** [typeorm/typeorm-typedi-extensions#8]
Hi there,
I'm trying to use these method:
https://github.com/typeorm/typeorm-typedi-extensions?#ormcustomrepository

But OrmCustomRepository  does not exist :
import { OrmCustomRepository } from "typeorm-typedi-extensions";

**Comment by booradleys** [comment]
It seems correct path is:
import {OrmCustomRepository} from "../node_modules/typeorm-typedi-extensions/decorators/OrmCustomRepository";

**Comment by pleerock** [comment]
fixed in `0.0.10`
