### ISSUE TITLE
typeorm-typedi-extensions@0.0.10 requires a peer of typeorm@^0.0.9 but none was installed.

### ISSUE THREAD

**Issue by valVk** [typeorm/typeorm-typedi-extensions#9]
And again problem with peer dependency

![selection_20170329_047f413](https://cloud.githubusercontent.com/assets/1130626/24458811/ad96fe40-14a2-11e7-8e35-445abb8ac8d1.png)

**Comment by pleerock** [comment]
yeah thats a pain to update it to the last version each time.... fixed in latest version

**Comment by valVk** [comment]
Thanks!!!
